### ISSUE TITLE
Debugging Support

### ISSUE THREAD

**Issue by rudyjahchan** [stormpath/stormpath-sdk-ruby#10]
In using the SDK, it would be convenient to be able to instantiate a client with a debugging option - which would then output requests/responses to the Rails logs/STDOUT.

The SDKs should use a common logger. This logger should be overridable and should be overridden to Rails.logger in Rails environments. For example:

require 'logger'

module Stormpath
  def self.logger
    @logger ||= Logger.new(STDOUT)
  end

  def self.logger=(logger)
    @logger = logger
  end
end

Suggestions:

1. Add a configurable logger to the base Stormpath module, using SLF4R or rolling our own (based on investigation)
1. Add a debugging flag to Stormpath::Client

### Follow up Issues

1. Have the stormpath-rails gem set the logger to be Rails.logger
1. Update the stormpath gems to use this logger

**Comment by omgitstom** [comment]
We have a new rails integration here.  
https://github.com/stormpath/stormpath-rails

Talking with a few developers, it seems like the logging is sufficient for the package.  If you have any questions / suggestions / feature enhancements for logging, please open an issue on stormpath-rails.
