### ISSUE TITLE
Organization Defects

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-sdk-ruby#108]
- 1

The following: 
orgs = @client.organizations.search name: 'whatever' 
puts orgs.first

Produces:

/Users/[removed]/.rvm/gems/ruby-2.1.1/gems/stormpath-sdk-1.0.0/lib/stormpath-sdk/data_store.rb:134:in `execute_request': Request method 'GET' not supported (Stormpath::Error)

from /Users/[removed]/.rvm/gems/ruby-2.1.1/gems/stormpath-sdk-1.0.0/lib/stormpath-sdk/data_store.rb:56:in `get_resource'

from /Users/[removed]/.rvm/gems/ruby-2.1.1/gems/stormpath-sdk-1.0.0/lib/stormpath-sdk/resource/base.rb:214:in `materialize'

from /Users/[removed]/.rvm/gems/ruby-2.1.1/gems/stormpath-sdk-1.0.0/lib/stormpath-sdk/resource/base.rb:164:in `get_property'

from /Users/[removed]/.rvm/gems/ruby-2.1.1/gems/stormpath-sdk-1.0.0/lib/stormpath-sdk/resource/collection.rb:94:in `items'

from /Users/[removed]/.rvm/gems/ruby-2.1.1/gems/stormpath-sdk-1.0.0/lib/stormpath-sdk/resource/collection.rb:77:in `iterate'

from /Users/[removed]/.rvm/gems/ruby-2.1.1/gems/stormpath-sdk-1.0.0/lib/stormpath-sdk/resource/collection.rb:60:in `each'

from /Users/[removed]/.stormpath/spwrapper.rb:44:in `first'

from /Users/[removed]/.stormpath/spwrapper.rb:44:in `getOrgs'

- 2

Password reset needs the ability to set the organizational name key.  Checking the code, it looks like this method doesn't support account store href as well.

**Comment by omgitstom** [comment]
@nikone looks like this is not working correctly, please prioritized for this week

**Comment by DamirSvrtan** [comment]
@omgitstom - the issue from your first point is the same as #112. I made a PR for that.

**Comment by DamirSvrtan** [comment]
Hey @omgitstom,

I've been searching the documentation and am unable to find a code sample where you can provide the organization nameKey when reseting the password.

Could you provide me with a link?

**Comment by DamirSvrtan** [comment]
The issue number 2 here is fixed with #117 . Waiting for @ecrisostomo to merge. No matter what, it will fail until the saml integration is merged since I'm using some new Ruby syntax and the tests on master are still using Ruby 1.9.3.

**Comment by DamirSvrtan** [comment]
Fixed. WIll be pushed in new version.
