### ISSUE TITLE
Remove support for Ruby 1.9.3, Add support for 2.2 and 2.3

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-sdk-ruby#115]
Ruby 1.9.3 was EOL in Feb 2015

**Comment by DamirSvrtan** [comment]
Ruby 2.0.0 was EOL in Feb 2016. Sorry, didn't know that: https://www.ruby-lang.org/en/news/2016/02/24/support-plan-of-ruby-2-0-0-and-2-1/

**Comment by DamirSvrtan** [comment]
I've removed both versions in PR #109

**Comment by DamirSvrtan** [comment]
Removed.
