### ISSUE TITLE
NoMethodError in Stormpath::Rails::SessionsController#create

### ISSUE THREAD

**Issue by dangersorus** [stormpath/stormpath-sdk-ruby#124]
Hey - I'm getting this: from clean rails install. 
Rails 4.2.5 - gem 'stormpath-rails', '~> 1.1.2.beta'

NoMethodError in Stormpath::Rails::SessionsController#create
undefined method `index' for nil:NilClass               
stormpath-sdk (1.1.0) lib/stormpath-sdk/resource/associations.rb:62:in `get'
 if can.include? :get
                  def get(id_or_href, expansion=nil)
                    item_href = if id_or_href.index '/'
                      id_or_href
                    else
                      "#{href}/#{id_or_href}

stack:
stormpath-sdk (1.1.0) lib/stormpath-sdk/resource/associations.rb:62:in `get'
stormpath-rails (1.1.2.beta) lib/stormpath/rails/client.rb:83:in `application'
stormpath-rails (1.1.2.beta) lib/stormpath/rails/client.rb:20:in `authenticate'
stormpath-rails (1.1.2.beta) lib/stormpath/rails/authentication.rb:11:in `authenticate'
stormpath-rails (1.1.2.beta) app/controllers/stormpath/rails/sessions_controller.rb:5:in `create'
actionpack (4.2.5) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (4.2.5) lib/abstract_controller/base.rb:198:in `process_action'
actionpack (4.2.5) lib/action_controller/metal/rendering.rb:10:in `process_action'

**Comment by cilim** [comment]
Hey @dangersorus! I too created a new Rails 4.2.5 app and installed the stormpath-rails gem:

```ruby
gem 'stormpath-rails', '~> 2.0.0'
```

After following the instructions everything works. Can you try and update your version to 2.0.0 and let us know if you still have errors?

Thanks!
