### ISSUE TITLE
Email Whitelist and Blacklist Configuration Support

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-sdk-ruby#134]
https://stormpath.atlassian.net/browse/AM-2889

**Comment by cilim** [comment]
PR: https://github.com/stormpath/stormpath-sdk-ruby/pull/142
Please review @DamirSvrtan

**Comment by DamirSvrtan** [comment]
Closing since this was merged with #142

**Comment by cilim** [comment]
Reopening cause the functionality could use a bit more of a friendly interface for adding/removing from blacklist/whitelist.

Currently, the SDK doesn't deal with that, it just creates the array of domains, rewriting all existing ones in the collection.

**Comment by cilim** [comment]
PR created, please review @DamirSvrtan

**Comment by cilim** [comment]
The improved interface for handling whitelists/blacklists is rejected.
