### ISSUE TITLE
send_password_reset_email does not raise exception if directory does not allow this workflow

### ISSUE THREAD

**Issue by tilo** [stormpath/stormpath-sdk-ruby#158]
when `application.send_password_reset_email` is being called with a Facebook email address, 
and the corresponding Stormpath Facebook dictionary has all the Workflows disabled, 
the Ruby SDK still behaves as if it successfully sent out an email (but does not send the email).

Expected behavior:
     - API call raises exception , e.g. can not send pwd reset email to that email
     - no email should be sent

Observed behavior:

When I call the API to trigger sending of a password reset email, the API call returns successfully, and incorrectly returns the HREF of the account in that Facebook Directory.
No email is being sent.

**Comment by cilim** [comment]
@tilo, just to verify, by Stormpath Facebook dictionary, you meant directory, right?

**Comment by tilo** [comment]
I meant Stormpath Directory of type "Facebook"

**Comment by omgitstom** [comment]
This is a REST issue.   Please contact for information

**Comment by tilo** [comment]
Is there an ETO on when this can get fixed? It looks like an invalid  API response.
