### ISSUE TITLE
[IMPORTANT] Modify tests to use @testmail.stormpath.com

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-sdk-ruby#181]
This is a commercial account that I set up backed by mailinator.com for our own testing and QA purposes.  They have a rest API that we can use to send/check email too if SMTP isnt good enough.  This can be useful for engineering to assert that mail has been received in Integration Tests if desired.

**Comment by cilim** [comment]
I'll mark this as duplicate since I'll attend to this issue in https://github.com/stormpath/stormpath-sdk-ruby/issues/169
