### ISSUE TITLE
Support workflow overrides when creating an Application Account

### ISSUE THREAD

**Issue by lhazlewood** [stormpath/stormpath-sdk-ruby#41]
For example, just like the [Directory](https://github.com/stormpath/stormpath-sdk-ruby/blob/master/lib/stormpath-sdk/resource/directory.rb) resource:

    def create_account account, registration_workflow_enabled=nil
        href = accounts.href
        unless registration_workflow_enabled.nil?
            href += "?registrationWorkflowEnabled=#{registration_workflow_enabled.to_s}"
        end

        data_store.create href, account, Stormpath::Resource::Account
    end

**Comment by nikone** [comment]
closing this, changes are merged.

https://github.com/stormpath/stormpath-sdk-ruby/pull/100
