### ISSUE TITLE
API key secret with forward slash in it cause spec/resources/application_spec.rb:23 to fail

### ISSUE THREAD

**Issue by liquidautumn** [stormpath/stormpath-sdk-ruby#47]
While setting up test environment I've got such secret generated and it caused URI to be malformed when load application from composite url.
Secret causing failure is "tWTm8kfpwogF/FBvraXe+Mon8sEymMhR5FMfejSokJc"

Seems like I've got lucky on it, should be quite rare occasion.

**Comment by cilim** [comment]
The spec is failing because Ruby can't handle creating a uri instance if there's a forward slash in the userinfo part of the composite url:

```
composite_url = https://1Y_client_id_XW08:ExJri_client_secret_qZFfF/zE05Y0Wx1jI6uEO60cG8RXQ@api.stormpath.com/v1/applications/66uVmRrephr9uudwBd3LBh"
URI(composite_url) # => failing here
```

Currently, the instruction is removed from the readme until further notice.

**Comment by cilim** [comment]
This fixes the issue and all specs are passing. The URI module still doesn't know how to handle URL's with userinfo that have forward slashes, but found a way to solve with regex.

Please review, or discuss a better way to do it.

**Comment by DamirSvrtan** [comment]
Congrats to @cilim for fixing this ancient bug!
