### ISSUE TITLE
Make entire custom_data hash available on Account

### ISSUE THREAD

**Issue by arvindhsukumar** [stormpath/stormpath-sdk-ruby#60]
Right now, account.custom_data returns an instance of Stormpath::Resource::CustomData, which needs to be queried on a key-to-key basis.

Is there any reason why the entire data isn't made accessible from this object after calling this method (when expansion is used)? Especially when the default behaviour in the REST API is to include the entire data in the response.

Making the entire hash available would be useful for anyone who doesn't know  in advance what keys are included in the custom_data.

EDIT: This seems more a bug than anything else. When I tried accessing one of the properties in custom_data, all the other properties got magically filled in. So, for the moment, if you need the entire hash, try to access _some_ property in account.custom_data (even if it doesnt exist). You'll then have access to the other properties as well in account.custom_data.properties .

Regards,
Arvindh

**Comment by jibiabraham** [comment]
It would be terrific if this were documented somewhere. I've just spent hours debugging this very issue.

**Comment by cilim** [comment]
@jibiabraham sorry for the inconvenience. We'll add a note for this behaviour in the documentation.
