### ISSUE TITLE
Querying for Created At and Modified At time for Resources

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-sdk-ruby#70]
http://docs.stormpath.com/rest/product-guide/#search

Search for Datetime Search

**Comment by nikone** [comment]
Hi Tom,

before going any further with this issue can you check if the following specification ok?

## Datetime Search

applications created between Jan 12, 2015 and Jan 14, 2015 you would request
```ruby
client.applications.search( created_at: [ first_date, second_date ] )
```
applications modified between Jan 12, 2015 and Jan 14, 2015 you would request
```ruby
client.applications.search( modified_at: [ first_date, second_date ] )
```
### precision and format

first_date and second_date can be string '2015-01-12' or object Date.today.iso8601
also you can pass a variation of formats for example only a year '2015' or full datetime '2015-01-12T12:00:00'
useful for queries where the range can be encapsulated in a particular year, month, day, hour, minute or second.

### exclusion vs inclusion

For example, if you wanted to get all applications created between Jan 12, 2015 and Jan 14, 2015 not including the 14th, you would request:
```ruby
client.applications.search( modified_at: [ { include: '2015-01-12' }, { exclude: '2015-01-14' } ])
```
if the include/exclude field isn't set it is include by default

### shorthand
createdAt and modifiedAt can use shorthand for the range to simplify the query parameter. This is useful for queries
where the range can be encapsulated in a particular year, month, day, hour, minute or second.

For example if you wanted all applications created in Jan 2015 :
```ruby
client.applications.search( created_at: '2015-01' )
```

**Comment by omgitstom** [comment]
Nenad had a statement:

```
What I find weird here is that i was looking on other SDK implementations and i didn’t find this feature implemented on any of them. I found the specifics in the documentation under Datetime Search http://docs.stormpath.com/rest/product-guide/#search
```

With some of the SDKs, what they do is pass through the information to the query.  So for example, in node, I can specify a map of options like...

```
application.getAccounts({"createdAt": "[2015-06-12]"},function(err, accounts){...});
```
There will not be code that will be specific to the feature, but it is passing the parameter directly to the query.  Which brings up my question - what is the value in doing it with specific params (like gt, gte, lte, lt)  instead of doing the same pass through technique?
