### ISSUE TITLE
Provide Quickstart Code

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-sdk-ruby#89]
We are adding new quickstarts to the Admin Console, Brent was trying to get the template down, but was having issues.  Below is the markdown, please fill in the rest and send to brent@stormpath.com.  Thanks!

## Install the Stormpath Library

Install the SDK: 

```bash
gem install stormpath-sdk --pre
```

## Set API Key

Configure the library with your Stormpath API Keys:

```
```

## Require the SDK

```
require 'stormpath-sdk'
```

## Create a Client

```
```

## Retrieve Your Application

You'll need an Application resource to work with users in Stormpath, so we've created one for you. Retrieve it via:

```
application = client.applications.get {{ application_url }}
```

## Create a User Account

Use the Application to create a new Account:

```
account = application.accounts.create({
  given_name: 'Joe',
  surname: 'Stormtrooper',
  username: 'tk421', 
  email: 'tk421@stormpath.com',
  customData: {
  	favorite_color: 'white'
  },
  password: '4P@$$w0rd!'
})
```

## Retrieve the Account

Use the Application to retrieve the new Account:

```
accounts = application.accounts.search('Joe').limit(50)order('given_name')
accounts.each do |account|
    puts "#{account.given_name} #{acc.surname}"
end
```

## Authenticate the Account

Use the Application to authenticate the Account:

```
auth_request =
  Stormpath::Authentication::UsernamePasswordRequest.new 'tk421@stormpath.com', '4P@$$w0rd!'

result = application.authenticate_account(auth_request)
```

## Send a Password Reset Email

If the user forgets their password, use the Application to send them a
reset-password email:

```
account = application.send_password_reset_email 'tk421@stormpath.com'
```

## Reset a User's Password

The email should include a link to a page where the user can enter a new
password. Use the token to get the password:

```
get '/users/reset' do
  token = params[:sptoken]
  account = application.verify_password_reset_token token
  #proceed to update session, display account, etc
end
```

Collect the user's password and update their Account:

```
account.password = new_password
  account.save
  ```
  

## That's It!

That's all you have to do to sign up and login users with Stormpath.

**Comment by nikone** [comment]
I added the missing parts and also fixed some mistakes.
```
client.applications.get {{ application_url }}
```
we dont't need the curly braces 
```
limit(50)order('given_name')
```
missing the dot



Here is the full document

## Install the Stormpath Library

Install the SDK: 

```bash
gem install stormpath-sdk --pre
```

## Set Environment Variables

Configure the SDK by using environment variables:

```bash
$ export STORMPATH_CLIENT_APIKEY_ID=3KCTS6CCEIJFK5I8FS7GRWFBT
$ export STORMPATH_CLIENT_APIKEY_SECRET=Arlvn2tUjjB/YjdrC+m+PiBGVTYlmRgCi+sA6vixkDQ
$ export STORMPATH_APPLICATION_HREF=https://api.stormpath.com/v1/applications/6h2I12HwX5BjS2BlYIGn5s
```

## Require the SDK

```
require 'stormpath-sdk'
```

## Create a Client
The first step to working with Stormpath is creating a instance of Stormpath Client

```ruby
client = Stormpath::Client.new api_key: { id: ENV['STORMPATH_CLIENT_APIKEY_ID'], secret: ENV['STORMPATH_CLIENT_APIKEY_SECRET'] }
```


## Retrieve Your Application

You'll need an Application resource to work with users in Stormpath, so we've created one for you. Retrieve it via:

```ruby
application = client.applications.get application_url
```


## Create a User Account

Create an account via application instance with accounts.create

```ruby
account = application.accounts.create({
  given_name: 'Joe',
  surname: 'Stormtrooper',
  username: 'tk421', 
  email: 'tk421@stormpath.com',
  customData: {
  	favorite_color: 'white'
  },
  password: '4P@$$w0rd!'
})
```


## Retrieve the Account

You can also search the accounts binded to the application:

```ruby
accounts = application.accounts.search('Joe').limit(50).order('givenName')
accounts.each do |account|
  puts "#{account.given_name} #{acc.surname}"
end
```


## Authenticate the Account

Use the Application to authenticate the Account:

```ruby
auth_request =
  Stormpath::Authentication::UsernamePasswordRequest.new 'tk421@stormpath.com', '4P@$$w0rd!'

result = application.authenticate_account(auth_request)
```

## Send a Password Reset Email

If the user forgets their password, use the Application to send them a
reset-password email:

```ruby
account = application.send_password_reset_email 'tk421@stormpath.com'
```


## Reset a User's Password

The email should include a link to a page where the user can enter a new
password. Use the token to get the password:

```ruby
get '/users/reset' do
  token = params[:sptoken]
  account = application.verify_password_reset_token token
  #proceed to update session, display account, etc
end
```

Collect the user's password and update their Account:

```ruby
account.password = new_password
account.save
```
  

## That's It!

That's all you have to do to sign up and login users with Stormpath.
